import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Check if the auth token exists to verify Admin status
  const cookieStore = await cookies();
  const token = cookieStore.get("token");
  const isAdmin = !!token; // If token exists, they are logged in

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Navigation Bar */}
        <nav style={{ padding: "16px", backgroundColor: "#111", color: "white", display: "flex", gap: "20px" }}>
          <Link href="/">Home</Link>
          <Link href="/login">Login</Link>
          
          {/* Conditional Admin Menu */}
          {isAdmin && (
            <Link href="/user" style={{ color: "lightblue" }}>
              User Management
            </Link>
          )}
        </nav>
        
        <main style={{ padding: "24px" }}>
          {children}
        </main>
      </body>
    </html>
  );
}